server.port=8081
spring.application.name=spring-boot-app

spring.datasource.url=jdbc:postgresql://sombathawspostgresql-184.cru66siewg1o.ap-southeast-2.rds.amazonaws.com:5432/cicdawspg
spring.datasource.username=postgres
spring.datasource.password=PA$$word2026
spring.jpa.hibernate.ddl-auto=update

jwt.secret=vNVac9/LRd25QkZJyJXfrjioKvAWHVoqbh8kZBfUyLo/n9xsTm7LoJBnNNlcEBByIJzTHmmWX3A/qd0jAOyPWw==
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

